name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-release:
    name: publish release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: 🔗 Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
      - name: 💎 Install
        run: |
          python -m pip install --no-cache-dir -r requirements-dev.txt
      - name: 💃 Build release
        run: |
          python setup.py clean --all sdist bdist_wheel
      - name: 📦 Publish release to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
        with:
            password: ${{ secrets.pypi_password }}
